import {
    HOME_FAAS_DESKTOP_WEBP,
    HOME_FAAS_DESKTOP_JPG,
    HOME_FAAS_MOBILE_WEBP,
    HOME_FAAS_MOBILE_JPG,
} from '@/config/imageConfigs/home';

const faasStyle = (theme) => ({
    root: {
        display: 'flex',
        justifyContent: 'center',
        height: '600px',
        width: '100%',
        flexWrap: 'wrap',
        backgroundSize: 'contain',
        backgroundPosition: '0% 50%',
        backgroundImage: `url(${HOME_FAAS_DESKTOP_WEBP.src}), url(${HOME_FAAS_DESKTOP_JPG.src})`,
        backgroundRepeat: 'no-repeat',
        [theme.breakpoints.down('sm')]: {
            backgroundSize: '100%',
            backgroundImage: `url(${HOME_FAAS_MOBILE_WEBP.src}), url(${HOME_FAAS_MOBILE_JPG.src})`,
            backgroundPosition: 'bottom',
            minHeight: '800px',
            height: 700,
        },
        [theme.breakpoints.down('xs')]: {
            minHeight: '600px',
        },
    },
    text: {
        backgroundColor: 'transparent',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        height: '100%',
        [theme.breakpoints.down('sm')]: {
            padding: '0px',
            justifyContent: 'flex-start',
        },
    },
    title: {
        backgroundColor: 'transparent',
        fontFamily: 'FuturaPT',
        fontSize: '32px',
        color: 'black',
        height: 'auto',
        marginTop: '5%',
        paddingLeft: '40%',
        paddingBottom: '10px',
        width: '100%',
        position: 'relative',
        [theme.breakpoints.down('sm')]: {
            padding: '10px',
            paddingBottom: '0px',
            fontSize: '22px',
            textAlign: 'center',
        },
    },
    new: {
        position: 'absolute',
        width: '60px',
        left: '26%',
        bottom: '50%',
        [theme.breakpoints.down('xs')]: {
            width: 45,
            left: '8%',
        },
    },
    subtitle: {
        backgroundColor: 'transparent',
        fontFamily: 'Avenir-Medium, sans-serif',
        fontSize: '20px',
        color: 'black',
        width: 'auto',
        height: 'auto',
        paddingLeft: '40%',
        paddingRight: '10%',
        paddingBottom: '10px',
        [theme.breakpoints.down('sm')]: {
            padding: '20px',
            paddingBottom: '0px',
            width: '100%',
            textAlign: 'center',
            fontSize: '18px',
        },
    },
    serviceContainer: {
        backgroundColor: 'transparent',
        display: 'flex',
        justifyContent: 'flex-start',
        width: '100%',
        height: 'auto',
        paddingLeft: '40%',
        paddingBottom: '10px',
        [theme.breakpoints.down('sm')]: {
            padding: '20px',
            textAlign: 'center',
            justifyContent: 'center',
        },
    },
    services: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '90px',
    },
    serviceText: {
        fontSize: '16px',
        textAlign: 'center',
    },
    serviceIcons: {
        height: '70px',
        width: '70px',
    },
    learnMoreContainer: {
        backgroundColor: 'transparent',
        display: 'flex',
        justifyContent: 'flex-start',
        width: '100%',
        height: 'auto',
        paddingLeft: '40%',
        [theme.breakpoints.down('sm')]: {
            paddingLeft: '0px',
            textAlign: 'center',
            justifyContent: 'center',
        },
    },
    learnMoreButton: {
        border: 'solid 1px black',
        borderRadius: '20px',
        padding: '5px 35px 5px',
        textTransform: 'none',
    },
});

export default faasStyle;
