const footerStyle = (theme) => ({
    root: {
        width: '100%',
        height: 'auto',
        backgroundColor: '#434343',
        fontFamily: 'Avenir',
        color: '#ffffff',
    },
    container: {
        display: 'flex',
        flexDirection: 'column',
        padding: '40px 65px 0px',
        [theme.breakpoints.down('sm')]: {
            padding: '30px 30px 0px',
        },
    },
    gridContainer: {
        width: '100%',
        height: 'auto',
    },
    gridItem: {
        flexWrap: 'wrap',
        maxHeight: '160px',
    },
    gridTitle: {
        fontSize: '18px',
        fontWeight: '800',
        paddingBottom: '25px',
        fontFamily: 'Avenir',
        height: '55px',
        width: '100%',
    },
    gridItemContainer: {
        width: '100%',
        height: '120px',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
    },
    linkButtonContainer: {
        width: '50%',
        [theme.breakpoints.down('sm')]: {
            width: '100%',
        },
    },
    linkButton: {
        textTransform: 'none',
        fontFamily: 'Avenir',
        width: 'auto',
        padding: '0px 3px',
        color: '#ffffff',
        justifyContent: 'flex-start',
        fontWeight: '500',
        fontSize: '16px',
    },
    socialLinkContainer: {
        width: '100%',
        height: '55px',
        paddingBottom: '25px',
        display: 'flex',
        justifyContent: 'flex-end',
        [theme.breakpoints.down('sm')]: {
            justifyContent: 'flex-start',
            paddingTop: '25px',
            paddingBottom: '0px',
        },
    },
    iconButton: {
        width: '30px',
        height: '30px',
        marginLeft: '30px',
        padding: '5px',
        backgroundColor: 'white',
        '&,&:hover,&:focus': {
            backgroundColor: 'white',
        },
        [theme.breakpoints.down('sm')]: {
            marginLeft: '0px',
            marginRight: '30px',
        },
    },
    emailContainer: {
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        flexDirection: 'column',
        width: '100%',
        [theme.breakpoints.down('sm')]: {
            padding: '0px 0px 50px',
        },
    },
    emailInputRoot: {
        marginTop: '10px',
        height: '30px',
        width: '100%',
    },
    emailForm: {
        display: 'flex',
        flexDirection: 'row',
    },
    input: {
        backgroundColor: '#c6c6c6',
        width: 'calc(100% - 40px)',
        height: '30px',
        borderTopLeftRadius: '5px',
        borderBottomLeftRadius: '5px',
    },
    submitButton: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    submitButtonContainer: {
        margin: 0,
        padding: 0,
        borderTopRightRadius: '5px',
        borderBottomRightRadius: '5px',
        width: '32px',
        height: '30px',
        backgroundColor: '#f7cd3d',
        display: 'flex',
    },
    blackTriangle: {
        width: '10.5px',
        height: '12.5px',
    },
    divider: {
        backgroundColor: 'rgba(255, 255, 255, 0.6);',
        height: '1px',
        margin: '30px 0px 20px',
        [theme.breakpoints.down('sm')]: {
            margin: '30px 0px 15px',
        },
    },
    bottomGrid: {
        width: '100%',
        display: 'flex',
        justifyContent: 'space-between',
        paddingBottom: '30px',
        [theme.breakpoints.down('sm')]: {
            flexDirection: 'column',
        },
    },
    termsLinkText: {
        display: 'flex',
        cursor: 'pointer',
        fontSize: '15px',
        fontWeight: '500',
        fontFamily: 'Avenir',
        alignItems: 'center',
        [theme.breakpoints.down('sm')]: {
            paddingTop: '10px',
        },
    },
    flagButton: {
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        padding: '10px',
        width: '150px',
    },
    flag: {
        display: 'flex',
        width: '40px',
        height: '26px',
    },
    flagText: {
        color: '#ffffff',
        fontFamily: 'Avenir',
        textTransform: 'none',
        paddingLeft: '15px',
        fontSize: '16px',
        fontWeight: '500',
    },
    accordionContainer: {
        position: 'absolute',
        width: '100vw',
        left: 'calc((100% - 100vw)/2)',
    },
    accordionDetails: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: 0,
        color: '#434343',
        fontFamily: 'Avenir',
    },
    accordionTitle: {
        backgroundColor: '#f7cd3d',
        fontSize: '16px',
        fontWeight: '500',
        height: '60px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    accordionFlagsContainer: {
        maxWidth: '960px',
        padding: '40px 0px',
        width: '100%',
    },
    accordionFlagsButton: {
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        padding: '10px 10px',
        width: '100%',
    },
    accordionFlagsText: {
        color: '#434343',
        fontFamily: 'Avenir',
        textTransform: 'none',
        paddingLeft: '16px',
        fontSize: '16px',
        fontWeight: '500',
    },
    customAccordion: {
        backgroundColor: 'transparent',
    },
    customAccordionHeader: {
        color: '#ffffff',
        fontWeight: '800',
        fontSize: '18px',
    },
    customAccordionList: {
        // color: '#ffffff',
        display: 'flex',
        flexDirection: 'column',
    },
});

export default footerStyle;
