const headerLinksStyle = (theme) => ({
    list: {
        margin: 0,
        padding: '0',
        listStyle: 'none',
        height: '100%',
    },
    listItem: {
        float: 'left',
        display: 'flex',
        height: '100%',
        width: 'auto',
        margin: '0',
        padding: '0',
        [theme.breakpoints.down('sm')]: {
            width: '100%',
            height: '70px',
        },
    },
    button: {
        position: 'relative',
        color: '#434343',
        height: '100%',
        fontFamily: 'FuturaPT',
        padding: '10px 16px 10px',
        fontWeight: '500',
        fontSize: '16px',
        borderRadius: '3px',
        textDecoration: 'none',
        margin: '0px',
        display: 'inline-flex',
        textTransform: 'none',
        lineHeight: 'normal',
        [theme.breakpoints.down('md')]: {
            padding: '10px 9px 10px',
        },
        [theme.breakpoints.down('sm')]: {
            fontFamily: 'Avenir',
            paddingLeft: '37px',
            width: '100%',
            margin: '0px',
            height: '70px',
            fontSize: '20px',
            textAlign: 'center',
            alignItems: 'center',
            justifyContent: 'flex-start',
        },
    },
    productList: {
        zIndex: 1200,
        padding: 0,
        margin: 0,
        backgroundColor: '#f5f5f5',
        transformOrigin: '50% 0 0',
        position: 'absolute',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        left: '0px',
        right: '0px',
        top: '76px',
        width: '100%',
        height: '85px',
        [theme.breakpoints.down('sm')]: {
            top: '70px',
            flexDirection: 'column',
            height: '150px',
        },
    },
    divider: {
        width: '1px',
        height: '30px',
        backgroundColor: '#434343',
        [theme.breakpoints.down('sm')]: {
            display: 'none',
        },
    },
    expandMore: {
        transition: 'transform .5s',
        transform: 'rotate(180deg)',
    },
    expandLess: {
        transition: 'transform .5s',
        transform: 'rotate(0)',
    },
    moveDown: {
        transition: 'transform .5s',
        transform: 'translate(0px, 150px)',
    },
    moveUp: {
        transition: 'transform .5s',
        transform: 'translate(0px, 0px)',
    },
    drawerDivider: {
        margin: '5px auto',
        width: 'calc(100% - 40px)',
        backgroundColor: '#434343',
        height: '1px',
    },
    image: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        width: '25px',
        height: '25px',
        marginRight: '10px',
    },
    accountButton: {
        width: '100%',
    },
    accountText: {
        fontFamily: 'Avenir',
    },
    flag: {
        display: 'flex',
        width: '40px',
        height: '26px',
    },
    flagText: {
        color: '#434343',
        fontFamily: 'FuturaPT',
        textTransform: 'none',
        paddingLeft: '10px',
        fontSize: '20px',
        fontWeight: '500',
        height: 'auto',
        display: 'flex',
        [theme.breakpoints.down('sm')]: {
            fontFamily: 'Avenir',
        },
    },
});

export default headerLinksStyle;
